### ISSUE TITLE
color-blind-friendly representation

### ISSUE THREAD

**Issue by ooharak** [motemen/kanjile#1]
Summary:
A rounded square that enclose each character should be in a manner where a color blind user can distinguish between letters that have different correctness score.
[JA]色弱のため、部分的に合っている旨の枠表示が色だけだとわかりづらい場合があるため、線種を変えていただけますと嬉しいです。

Detail:
Each letter is currently enclosed by a rounded square of a different color according to its correctness score, but all kinds of square has exactly the same line style, making it difficult for a color blind user to distinguish.

Instead, it should have not only a different color, but also a different line style. or . e.g.:

- right letter in a right position --> 2px solid green
- right letter in a wrong position --> 1px dashed yellow
- wrong letter, right radical in a right position --> 1px solid orange
- wrong letter, right radical in a wrong position --> 1px dotted red

**Comment by motemen** [comment]
その他の声: https://twitter.com/mizunokura/status/1489988920356249602

**Comment by motemen** [comment]
https://github.com/motemen/kanjile/pull/3 やってみました。どうでしょう？

**Comment by ooharak** [comment]
ありがとうございます。Safariの場合に効かない部分があるようなので太枠にしてみました。 #4
